# Generated by Django 5.0.3 on 2026-01-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('bot', '0005_botstatus_adminnotificationsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'Вход в систему'), ('LOGOUT', 'Выход из системы'), ('DOCUMENT_CREATE', 'Создание документа'), ('DOCUMENT_EDIT', 'Редактирование документа'), ('DOCUMENT_DELETE', 'Удаление документа'), ('CATEGORY_CREATE', 'Создание категории'), ('CATEGORY_EDIT', 'Редактирование категории'), ('CATEGORY_DELETE', 'Удаление категории'), ('BOT_REQUEST', 'Запрос в боте'), ('FILE_DOWNLOAD', 'Скачивание файла'), ('UNAUTHORIZED_ACCESS', 'Попытка несанкционированного доступа')], max_length=50)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='bot.botuser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-timestamp'],
            },
        ),
    ]
