# Generated by Django 5.0.3 on 2026-01-13 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auditlog'),
        ('bot', '0007_alter_botstatus_last_heartbeat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botinteraction',
            options={'verbose_name': 'Взаимодействие', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AddField(
            model_name='botinteraction',
            name='django_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='botinteraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='bot.botuser'),
        ),
    ]
