# Generated by Django 5.0.3 on 2026-01-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='agreed_to_policy',
            field=models.BooleanField(default=False),
        ),
    ]
