# Generated by Django 5.0.3 on 2026-01-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botuser_agreed_to_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
