# Generated by Django 5.0.3 on 2026-01-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_botuser_email'),
        ('content', '0006_alter_category_options_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='subscribed_categories',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='content.category', verbose_name='Подписки на категории'),
        ),
    ]
