# Generated by Django 5.0.3 on 2026-01-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_botuser_subscribed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False, verbose_name='Работает')),
                ('last_heartbeat', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('error_message', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время запуска')),
            ],
            options={
                'verbose_name': 'Статус бота',
                'verbose_name_plural': 'Статус бота',
            },
        ),
        migrations.CreateModel(
            name='AdminNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID для уведомлений')),
                ('notify_on_errors', models.BooleanField(default=True, verbose_name='Уведомлять об ошибках')),
                ('notify_on_unauthorized', models.BooleanField(default=True, verbose_name='Уведомлять о попытках взлома')),
                ('notify_on_bot_down', models.BooleanField(default=True, verbose_name='Уведомлять о сбоях бота')),
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки уведомлений администратора',
                'verbose_name_plural': 'Настройки уведомлений администраторов',
            },
        ),
    ]
