# Generated by Django 5.0.3 on 2026-01-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_botstatus_adminnotificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='botstatus',
            name='last_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее уведомление о сбое'),
        ),
    ]
