# Generated by Django 5.0.3 on 2026-01-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_botstatus_last_alert_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botstatus',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность'),
        ),
    ]
