# Generated by Django 5.0.3 on 2026-01-03 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_document_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_type',
        ),
    ]
