# Generated by Django 5.0.3 on 2026-01-03 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_document_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.equipment'),
        ),
    ]
