# Generated by Django 5.0.3 on 2026-01-13 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_category_options_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Узел контента', 'verbose_name_plural': 'Дерево контента'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ (УСТАРЕЛО)', 'verbose_name_plural': 'Документы (УСТАРЕЛО)'},
        ),
        migrations.AlterModelOptions(
            name='documentversion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Версия файла', 'verbose_name_plural': 'Версии файлов'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='document',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_folder',
            field=models.BooleanField(default=True, verbose_name='Это папка'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='content_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.category'),
        ),
    ]
