# Generated by Django 5.0.3 on 2026-01-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='telegram_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
