# Generated by Django 5.0.3 on 2026-02-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_documentversion_telegram_file_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
