# Generated by Django 5.0.3 on 2026-03-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, help_text='Размер файла в байтах'),
        ),
    ]
